name: Infosec Compliance

on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]

jobs:
  scan:
    name: Code scan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: returntocorp/semgrep-action@v1
      with:
        publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
      continue-on-error: true
